In [1]:
import numpy as np

In [4]:
arr = np.arange(1,10)

In [8]:
# multiplication
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
# addition
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# division 
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [12]:
# subtraction 
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [13]:
# universal functions
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])