In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
# cast a list
arr = np.array(my_list)

In [4]:
my_mat = [[1,2,3],[4,5,6], [7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# create an array from 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# create an array containing zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# create an array containing ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# create an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# create a random uniformally distributed from 0 to 1
np.random.rand(5)

array([0.13973178, 0.02934507, 0.49890947, 0.43011809, 0.25838784])

In [13]:
# create 10 random integer from 0 to 100
np.random.randint(1,100,10 )

array([24, 79, 56, 36, 10, 71, 23, 12, 91, 43])

In [14]:
array1 = np.random.randint(0,50, 10)

In [18]:
# reshape the array
array1.reshape(2,5)

array([[34, 16, 17, 42, 38],
       [14,  7, 25, 20, 20]])

In [20]:
# return the max number of the array
array1.max()

42

In [21]:
# return index of minimum. index starts from 0
array1.argmin()

6