In [1]:
import numpy as np

In [22]:
# assign values to the array
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
# broadcasting
arr[0:4] = 100

In [6]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [8]:
# slice an array
slice_of_arr = arr[0:5]

In [10]:
slice_of_arr

array([100, 100, 100, 100,   4])

In [11]:
arr_copy = arr.copy()

In [12]:
arr_copy

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [15]:
# 2D arrays
arr_2d = np.array([[5,10,15], [20, 25, 30], [40, 50, 60]])

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [40, 50, 60]])

In [18]:
arr_2d[2][2]

60

In [20]:
arr_2d[2,2]

60

In [21]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [23]:
# conditional selection
# select elements larger than 5
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [24]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [25]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [26]:
array_2d = np.arange(50).reshape(5,10)

In [27]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])